# Generated by Django 5.2.12 on 2026-03-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data de saída')),
                ('data_prevista', models.DateField(verbose_name='Data prevista de devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data real de devolução')),
                ('Livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro emprestado')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='Leitor')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
